// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal_23AM.Context;

namespace ProyectoFinal_23AM.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProyectoFinal_23AM.Entities.Alumno", b =>
                {
                    b.Property<int>("PkMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int?>("FkGrado")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreTutor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkMatricula");

                    b.HasIndex("FkGrado");

                    b.ToTable("alumnos");
                });

            modelBuilder.Entity("ProyectoFinal_23AM.Entities.Calificaciones", b =>
                {
                    b.Property<int>("PkCalificaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Asistencia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Calificación")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("FkGrado")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FkMateria")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("FkMatricula")
                        .HasColumnType("int");

                    b.HasKey("PkCalificaciones");

                    b.HasIndex("FkGrado");

                    b.HasIndex("FkMateria");

                    b.HasIndex("FkMatricula");

                    b.ToTable("calificaciones");
                });

            modelBuilder.Entity("ProyectoFinal_23AM.Entities.Grados", b =>
                {
                    b.Property<int>("PkGrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Grado")
                        .HasColumnType("int");

                    b.HasKey("PkGrado");

                    b.ToTable("grados");
                });

            modelBuilder.Entity("ProyectoFinal_23AM.Entities.Materias", b =>
                {
                    b.Property<int>("PkMateria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Materia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkMateria");

                    b.ToTable("materias");
                });

            modelBuilder.Entity("ProyectoFinal_23AM.Entities.Observaciones", b =>
                {
                    b.Property<int>("PkObervaciones")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkMatricula")
                        .HasColumnType("int");

                    b.Property<string>("Observación")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkObervaciones");

                    b.HasIndex("FkMatricula");

                    b.ToTable("observaciones");
                });

            modelBuilder.Entity("ProyectoFinal_23AM.Entities.Rol", b =>
                {
                    b.Property<int>("PkRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProyectoFinal_23AM.Entities.Usuario", b =>
                {
                    b.Property<int>("PkUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("FkRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RFC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PkUsuario");

                    b.HasIndex("FkRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoFinal_23AM.Entities.Alumno", b =>
                {
                    b.HasOne("ProyectoFinal_23AM.Entities.Grados", "Grados")
                        .WithMany()
                        .HasForeignKey("FkGrado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grados");
                });

            modelBuilder.Entity("ProyectoFinal_23AM.Entities.Calificaciones", b =>
                {
                    b.HasOne("ProyectoFinal_23AM.Entities.Grados", "Grados")
                        .WithMany()
                        .HasForeignKey("FkGrado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal_23AM.Entities.Materias", "Materias")
                        .WithMany()
                        .HasForeignKey("FkMateria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProyectoFinal_23AM.Entities.Alumno", "Alumnos")
                        .WithMany()
                        .HasForeignKey("FkMatricula");

                    b.Navigation("Alumnos");

                    b.Navigation("Grados");

                    b.Navigation("Materias");
                });

            modelBuilder.Entity("ProyectoFinal_23AM.Entities.Observaciones", b =>
                {
                    b.HasOne("ProyectoFinal_23AM.Entities.Alumno", "Alumnos")
                        .WithMany()
                        .HasForeignKey("FkMatricula");

                    b.Navigation("Alumnos");
                });

            modelBuilder.Entity("ProyectoFinal_23AM.Entities.Usuario", b =>
                {
                    b.HasOne("ProyectoFinal_23AM.Entities.Rol", "Roles")
                        .WithMany()
                        .HasForeignKey("FkRol");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
